/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sports */
        get: {
            parameters: {
                query?: {
                    lang?: "zh" | "en";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            data?: {
                                items?: {
                                    key?: string;
                                    label?: string;
                                    category?: string;
                                    icon?: string;
                                    order?: number;
                                    is_active?: boolean;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming sessions */
        get: {
            parameters: {
                query?: {
                    sport_key?: string;
                    city?: string;
                    from?: string;
                    to?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            data?: {
                                sessions?: components["schemas"]["Session"][];
                                page?: components["schemas"]["Page"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            data?: {
                                session?: components["schemas"]["Session"];
                                meta?: components["schemas"]["SessionMeta"];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            data?: {
                                /** Format: uuid */
                                session_id?: string;
                                joined?: boolean;
                                meta?: components["schemas"]["SessionMeta"];
                            };
                        };
                    };
                };
            };
        };
        /** Leave a session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            data?: {
                                /** Format: uuid */
                                session_id?: string;
                                joined?: boolean;
                                meta?: components["schemas"]["SessionMeta"];
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check-in to a session (GPS + time window) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        lat: number;
                        lng: number;
                    };
                };
            };
            responses: {
                /** @description ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            data?: {
                                check_in?: components["schemas"]["CheckIn"];
                            };
                        };
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Outside time/radius or not allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Page: {
            limit?: number;
            offset?: number;
            has_more?: boolean;
        };
        Session: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: uuid */
            host_user_id?: string;
            sport_key?: string;
            title?: string;
            notes?: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string;
            place_name?: string;
            address?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            checkin_radius_m?: number;
            checkin_open_mins_before?: number;
            checkin_close_mins_after?: number;
            min_people?: number;
            max_people?: number | null;
            /** @enum {string} */
            status?: "draft" | "published" | "cancelled" | "completed";
            /** @enum {string} */
            visibility?: "public" | "unlisted";
        };
        SessionMeta: {
            participant_count?: number;
            spots_left?: number | null;
            is_joined?: boolean;
            viewer_has_joined?: boolean;
            viewer_has_checked_in?: boolean;
        };
        CheckIn: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            session_id?: string;
            /** Format: uuid */
            user_id?: string;
            /** Format: date-time */
            checked_in_at?: string;
            lat?: number;
            lng?: number;
            distance_m?: number;
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
