-- Seed world countries for nationality selection
INSERT INTO public.countries (key, name_zh, name_en, sort, is_active) VALUES
('AF','阿富汗','Afghanistan',10,true),
('AX','奧蘭群島','Åland Islands',20,true),
('AL','阿爾巴尼亞','Albania',30,true),
('DZ','阿爾及利亞','Algeria',40,true),
('AS','美屬薩摩亞','American Samoa',50,true),
('AD','安道爾','Andorra',60,true),
('AO','安哥拉','Angola',70,true),
('AI','安奎拉','Anguilla',80,true),
('AQ','南極洲','Antarctica',90,true),
('AG','安地卡及巴布達','Antigua & Barbuda',100,true),
('AR','阿根廷','Argentina',110,true),
('AM','亞美尼亞','Armenia',120,true),
('AW','荷屬阿魯巴','Aruba',130,true),
('AU','澳洲','Australia',140,true),
('AT','奧地利','Austria',150,true),
('AZ','亞塞拜然','Azerbaijan',160,true),
('BS','巴哈馬','Bahamas',170,true),
('BH','巴林','Bahrain',180,true),
('BD','孟加拉','Bangladesh',190,true),
('BB','巴貝多','Barbados',200,true),
('BY','白俄羅斯','Belarus',210,true),
('BE','比利時','Belgium',220,true),
('BZ','貝里斯','Belize',230,true),
('BJ','貝南','Benin',240,true),
('BM','百慕達','Bermuda',250,true),
('BT','不丹','Bhutan',260,true),
('BO','玻利維亞','Bolivia',270,true),
('BA','波士尼亞與赫塞哥維納','Bosnia & Herzegovina',280,true),
('BW','波札那','Botswana',290,true),
('BV','布威島','Bouvet Island',300,true),
('BR','巴西','Brazil',310,true),
('IO','英屬印度洋領地','British Indian Ocean Territory',320,true),
('VG','英屬維京群島','British Virgin Islands',330,true),
('BN','汶萊','Brunei',340,true),
('BG','保加利亞','Bulgaria',350,true),
('BF','布吉納法索','Burkina Faso',360,true),
('BI','蒲隆地','Burundi',370,true),
('KH','柬埔寨','Cambodia',380,true),
('CM','喀麥隆','Cameroon',390,true),
('CA','加拿大','Canada',400,true),
('CV','維德角','Cape Verde',410,true),
('BQ','荷蘭加勒比區','Caribbean Netherlands',420,true),
('KY','開曼群島','Cayman Islands',430,true),
('CF','中非共和國','Central African Republic',440,true),
('TD','查德','Chad',450,true),
('CL','智利','Chile',460,true),
('CN','中國','China',470,true),
('CX','聖誕島','Christmas Island',480,true),
('CC','科克斯（基靈）群島','Cocos (Keeling) Islands',490,true),
('CO','哥倫比亞','Colombia',500,true),
('KM','葛摩','Comoros',510,true),
('CG','剛果（布拉薩）','Congo - Brazzaville',520,true),
('CD','剛果（金夏沙）','Congo - Kinshasa',530,true),
('CK','庫克群島','Cook Islands',540,true),
('CR','哥斯大黎加','Costa Rica',550,true),
('CI','象牙海岸','Côte d’Ivoire',560,true),
('HR','克羅埃西亞','Croatia',570,true),
('CU','古巴','Cuba',580,true),
('CW','庫拉索','Curaçao',590,true),
('CY','賽普勒斯','Cyprus',600,true),
('CZ','捷克','Czechia',610,true),
('DK','丹麥','Denmark',620,true),
('DJ','吉布地','Djibouti',630,true),
('DM','多米尼克','Dominica',640,true),
('DO','多明尼加共和國','Dominican Republic',650,true),
('EC','厄瓜多','Ecuador',660,true),
('EG','埃及','Egypt',670,true),
('SV','薩爾瓦多','El Salvador',680,true),
('GQ','赤道幾內亞','Equatorial Guinea',690,true),
('ER','厄利垂亞','Eritrea',700,true),
('EE','愛沙尼亞','Estonia',710,true),
('SZ','史瓦帝尼','Eswatini',720,true),
('ET','衣索比亞','Ethiopia',730,true),
('FK','福克蘭群島','Falkland Islands',740,true),
('FO','法羅群島','Faroe Islands',750,true),
('FJ','斐濟','Fiji',760,true),
('FI','芬蘭','Finland',770,true),
('FR','法國','France',780,true),
('GF','法屬圭亞那','French Guiana',790,true),
('PF','法屬玻里尼西亞','French Polynesia',800,true),
('TF','法屬南部屬地','French Southern Territories',810,true),
('GA','加彭','Gabon',820,true),
('GM','甘比亞','Gambia',830,true),
('GE','喬治亞','Georgia',840,true),
('DE','德國','Germany',850,true),
('GH','迦納','Ghana',860,true),
('GI','直布羅陀','Gibraltar',870,true),
('GR','希臘','Greece',880,true),
('GL','格陵蘭','Greenland',890,true),
('GD','格瑞那達','Grenada',900,true),
('GP','瓜地洛普','Guadeloupe',910,true),
('GU','關島','Guam',920,true),
('GT','瓜地馬拉','Guatemala',930,true),
('GG','根息','Guernsey',940,true),
('GN','幾內亞','Guinea',950,true),
('GW','幾內亞比索','Guinea-Bissau',960,true),
('GY','蓋亞那','Guyana',970,true),
('HT','海地','Haiti',980,true),
('HM','赫德島及麥唐納群島','Heard & McDonald Islands',990,true),
('HN','宏都拉斯','Honduras',1000,true),
('HK','中國香港特別行政區','Hong Kong SAR China',1010,true),
('HU','匈牙利','Hungary',1020,true),
('IS','冰島','Iceland',1030,true),
('IN','印度','India',1040,true),
('ID','印尼','Indonesia',1050,true),
('IR','伊朗','Iran',1060,true),
('IQ','伊拉克','Iraq',1070,true),
('IE','愛爾蘭','Ireland',1080,true),
('IM','曼島','Isle of Man',1090,true),
('IL','以色列','Israel',1100,true),
('IT','義大利','Italy',1110,true),
('JM','牙買加','Jamaica',1120,true),
('JP','日本','Japan',1130,true),
('JE','澤西島','Jersey',1140,true),
('JO','約旦','Jordan',1150,true),
('KZ','哈薩克','Kazakhstan',1160,true),
('KE','肯亞','Kenya',1170,true),
('KI','吉里巴斯','Kiribati',1180,true),
('KW','科威特','Kuwait',1190,true),
('KG','吉爾吉斯','Kyrgyzstan',1200,true),
('LA','寮國','Laos',1210,true),
('LV','拉脫維亞','Latvia',1220,true),
('LB','黎巴嫩','Lebanon',1230,true),
('LS','賴索托','Lesotho',1240,true),
('LR','賴比瑞亞','Liberia',1250,true),
('LY','利比亞','Libya',1260,true),
('LI','列支敦斯登','Liechtenstein',1270,true),
('LT','立陶宛','Lithuania',1280,true),
('LU','盧森堡','Luxembourg',1290,true),
('MO','中國澳門特別行政區','Macao SAR China',1300,true),
('MG','馬達加斯加','Madagascar',1310,true),
('MW','馬拉威','Malawi',1320,true),
('MY','馬來西亞','Malaysia',1330,true),
('MV','馬爾地夫','Maldives',1340,true),
('ML','馬利','Mali',1350,true),
('MT','馬爾他','Malta',1360,true),
('MH','馬紹爾群島','Marshall Islands',1370,true),
('MQ','馬丁尼克','Martinique',1380,true),
('MR','茅利塔尼亞','Mauritania',1390,true),
('MU','模里西斯','Mauritius',1400,true),
('YT','馬約特島','Mayotte',1410,true),
('MX','墨西哥','Mexico',1420,true),
('FM','密克羅尼西亞','Micronesia',1430,true),
('MD','摩爾多瓦','Moldova',1440,true),
('MC','摩納哥','Monaco',1450,true),
('MN','蒙古','Mongolia',1460,true),
('ME','蒙特內哥羅','Montenegro',1470,true),
('MS','蒙哲臘','Montserrat',1480,true),
('MA','摩洛哥','Morocco',1490,true),
('MZ','莫三比克','Mozambique',1500,true),
('MM','緬甸','Myanmar (Burma)',1510,true),
('NA','納米比亞','Namibia',1520,true),
('NR','諾魯','Nauru',1530,true),
('NP','尼泊爾','Nepal',1540,true),
('NL','荷蘭','Netherlands',1550,true),
('NC','新喀里多尼亞','New Caledonia',1560,true),
('NZ','紐西蘭','New Zealand',1570,true),
('NI','尼加拉瓜','Nicaragua',1580,true),
('NE','尼日','Niger',1590,true),
('NG','奈及利亞','Nigeria',1600,true),
('NU','紐埃島','Niue',1610,true),
('NF','諾福克島','Norfolk Island',1620,true),
('KP','北韓','North Korea',1630,true),
('MK','北馬其頓','North Macedonia',1640,true),
('MP','北馬利安納群島','Northern Mariana Islands',1650,true),
('NO','挪威','Norway',1660,true),
('OM','阿曼','Oman',1670,true),
('QO','大洋洲邊疆群島','Outlying Oceania',1680,true),
('PK','巴基斯坦','Pakistan',1690,true),
('PW','帛琉','Palau',1700,true),
('PS','巴勒斯坦自治區','Palestinian Territories',1710,true),
('PA','巴拿馬','Panama',1720,true),
('PG','巴布亞紐幾內亞','Papua New Guinea',1730,true),
('PY','巴拉圭','Paraguay',1740,true),
('PE','秘魯','Peru',1750,true),
('PH','菲律賓','Philippines',1760,true),
('PN','皮特肯群島','Pitcairn Islands',1770,true),
('PL','波蘭','Poland',1780,true),
('PT','葡萄牙','Portugal',1790,true),
('PR','波多黎各','Puerto Rico',1800,true),
('QA','卡達','Qatar',1810,true),
('RE','留尼旺','Réunion',1820,true),
('RO','羅馬尼亞','Romania',1830,true),
('RU','俄羅斯','Russia',1840,true),
('RW','盧安達','Rwanda',1850,true),
('WS','薩摩亞','Samoa',1860,true),
('SM','聖馬利諾','San Marino',1870,true),
('ST','聖多美普林西比','São Tomé & Príncipe',1880,true),
('CQ','CQ','Sark',1890,true),
('SA','沙烏地阿拉伯','Saudi Arabia',1900,true),
('SN','塞內加爾','Senegal',1910,true),
('RS','塞爾維亞','Serbia',1920,true),
('SC','塞席爾','Seychelles',1930,true),
('SL','獅子山','Sierra Leone',1940,true),
('SG','新加坡','Singapore',1950,true),
('SX','荷屬聖馬丁','Sint Maarten',1960,true),
('SI','斯洛維尼亞','Slovenia',1970,true),
('SB','索羅門群島','Solomon Islands',1980,true),
('SO','索馬利亞','Somalia',1990,true),
('ZA','南非','South Africa',2000,true),
('GS','南喬治亞與南三明治群島','South Georgia & South Sandwich Islands',2010,true),
('KR','南韓','South Korea',2020,true),
('SS','南蘇丹','South Sudan',2030,true),
('ES','西班牙','Spain',2040,true),
('LK','斯里蘭卡','Sri Lanka',2050,true),
('BL','聖巴瑟米','St. Barthélemy',2060,true),
('SH','聖赫勒拿島','St. Helena',2070,true),
('KN','聖克里斯多福及尼維斯','St. Kitts & Nevis',2080,true),
('LC','聖露西亞','St. Lucia',2090,true),
('MF','法屬聖馬丁','St. Martin',2100,true),
('PM','聖皮埃與密克隆群島','St. Pierre & Miquelon',2110,true),
('VC','聖文森及格瑞那丁','St. Vincent & Grenadines',2120,true),
('SD','蘇丹','Sudan',2130,true),
('SR','蘇利南','Suriname',2140,true),
('SJ','挪威屬斯瓦巴及尖棉','Svalbard & Jan Mayen',2150,true),
('SE','瑞典','Sweden',2160,true),
('CH','瑞士','Switzerland',2170,true),
('SY','敘利亞','Syria',2180,true),
('TW','台灣','Taiwan',2190,true),
('TJ','塔吉克','Tajikistan',2200,true),
('TZ','坦尚尼亞','Tanzania',2210,true),
('TH','泰國','Thailand',2220,true),
('TL','東帝汶','Timor-Leste',2230,true),
('TG','多哥','Togo',2240,true),
('TK','托克勞群島','Tokelau',2250,true),
('TO','東加','Tonga',2260,true),
('TT','千里達及托巴哥','Trinidad & Tobago',2270,true),
('TN','突尼西亞','Tunisia',2280,true),
('TR','土耳其','Türkiye',2290,true),
('TM','土庫曼','Turkmenistan',2300,true),
('TC','土克斯及開科斯群島','Turks & Caicos Islands',2310,true),
('TV','吐瓦魯','Tuvalu',2320,true),
('UM','美國本土外小島嶼','U.S. Outlying Islands',2330,true),
('VI','美屬維京群島','U.S. Virgin Islands',2340,true),
('UG','烏干達','Uganda',2350,true),
('UA','烏克蘭','Ukraine',2360,true),
('AE','阿拉伯聯合大公國','United Arab Emirates',2370,true),
('GB','英國','United Kingdom',2380,true),
('US','美國','United States',2390,true),
('UY','烏拉圭','Uruguay',2400,true),
('UZ','烏茲別克','Uzbekistan',2410,true),
('VU','萬那杜','Vanuatu',2420,true),
('VA','梵蒂岡','Vatican City',2430,true),
('VE','委內瑞拉','Venezuela',2440,true),
('VN','越南','Vietnam',2450,true),
('WF','瓦利斯群島和富圖那群島','Wallis & Futuna',2460,true),
('EH','西撒哈拉','Western Sahara',2470,true),
('YE','葉門','Yemen',2480,true),
('ZM','尚比亞','Zambia',2490,true),
('ZW','辛巴威','Zimbabwe',2500,true)
ON CONFLICT (key) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_en = EXCLUDED.name_en,
  sort = EXCLUDED.sort,
  is_active = EXCLUDED.is_active;
