export {
  useOnboardingStore,
  type OnboardingStatus,
  type OnboardingData,
  type OnboardingRole,
  type SkillLevel,
  type PlayingStyle,
  type PlayFrequency,
  ROLE_STEP,
  PLAYER_INTRO_STEP,
  PLAYER_USERNAME_STEP,
  PLAYER_SPORTS_STEP,
  PLAYER_SKILL_STEP,
  PLAYER_STYLE_STEP,
  PLAYER_FREQUENCY_STEP,
  PLAYER_AVATAR_STEP,
  PLAYER_MOTIVATION_STEP,
  VENUE_DETAILS_STEP,
  VENUE_SPORTS_STEP,
  VENUE_COURTS_STEP,
  VENUE_PHOTO_STEP,
  VENUE_VERIFY_STEP,
} from '@/stores/onboarding.store'
